type MovieData = { [key: string]: string[] };

export const tripleWordFlicksterData: MovieData = {
	"TheGodfather": ["Mafia", "Horse", "Offer"],
  "PulpFiction": ["Burgers", "Dance", "Briefcase"],
  "TheDarkKnight": ["Bat", "Joker", "Gotham"],
  "ForrestGump": ["Run", "Shrimps", "Chocolates"],
  "JurassicPark": ["Dinosaurs", "Park", "Chaos"],
  "TheLionKing": ["Simba", "Pride", "Hakuna"],
  "TheMatrix": ["Neo", "Pills", "Reality"],
  "ToyStory": ["Woody", "Buzz", "Friends"],
  "TheShining": ["Maze", "Writer", "Twins"],
  "ShawshankRedemption": ["Prison", "Escape", "Hope"],
  "Inception": ["Dreams", "Cobb", "Totem"],
  "Titanic": ["Iceberg", "Ship", "Love"],
  "FightClub": ["Soap", "Tyler", "Rules"],
  "TheAvengers": ["Heroes", "Loki", "Assemble"],
  "EternalSunshine": ["Memory", "Love", "Erasure"],
  "TheBigLebowski": ["Dude", "Bowling", "Rug"],
  "GoodWillHunting": ["Math", "Therapist", "Genius"],
  "TheSocialNetwork": ["Facebook", "Zuckerberg", "Lawsuit"],
  "Casablanca": ["Piano", "Bogart", "Letters"],
  "Jaws": ["Shark", "Beach", "Boat"],
  "BladeRunner": ["Replicants", "Deckard", "Future"],
  "Gladiator": ["Rome", "Arena", "Revenge"],
  "TheNotebook": ["Love", "Rain", "Letters"],
  "Psycho": ["Motel", "Shower", "Mother"],
  "LaLaLand": ["Dance", "Music", "Dreams"],
  "StarWarsANewHope": ["Force", "Lightsaber", "Vader"],
  "TheExorcist": ["Possession", "Priest", "Demon"],
  "TheBreakfastClub": ["Detention", "Teens", "Secrets"],
  "GroundhogDay": ["Loop", "Weatherman", "Change"],
  "TheSixthSense": ["Ghost", "Whisper", "Twist"],
  "TheUsualSuspects": ["Lineup", "Heist", "Kobayashi"],
  "BackToTheFuture": ["Time", "DeLorean", "Doc"],
  "KillBill": ["Bride", "Revenge", "Sword"],
  "Whiplash": ["Drums", "Teacher", "Perfection"],
  "SchindlersList": ["Holocaust", "List", "Oskar"],
  "TheIncredibles": ["Family", "Superheroes", "Syndrome"],
  "TrumanShow": ["Reality", "Cameras", "Escape"],
  "WillyWonka": ["Chocolate", "Factory", "Golden"],
  "DeadPoetsSociety": ["Carpe", "Teacher", "Poetry"],
  "GoodFellas": ["Gangsters", "Narrator", "Betrayal"]
};
